# Cria um novo registro de vídeo

POST http://localhost:5000/videos
Content-Type: application/json

{
    "title": "Video 01",
    "description": "Esse é o primeiro vídeo da série.",
    "duration": 180
}

###

# Recupera o POST

GET http://localhost:5000/videos